include "#!./gradlew -q composeApp:printConveyorConfig"
include "/stdlib/jdk/21/amazon.conf"

app {
    machines = [windows.amd64, linux.aarch64, linux.arm64, mac.aarch64]

    display-name = "Help Quest"
    fsname = "helpquest"
    vendor = "AF"
    description = "Help Quest Application"
    rdns-name = "com.helpquest"

    url-schemes = ["helpquest"]

    inputs += "composeApp/build/libs/composeApp-desktop-*.jar"

    icons = "conveyorResources/logohq.png"

    single-instance = true

    license = "MIT"
;     copyright = "© 2026"
;     vcs-url = "https://github.com/ferrariniand/HelpQuest"
;     site.base-url="https://hq.com/downloads"
    updates = none

    jvm {
        main-class = "com.helpquest.MainKt"
        gui.main-class = "com.helpquest.MainKt"

        version = 21

        options = [
            "-Xmx2g",
            "--add-opens=java.base/sun.misc=ALL-UNNAMED",
            "--add-opens=java.base/java.nio=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt.wl=ALL-UNNAMED",
            "--add-opens=java.desktop/sun.awt.X11=ALL-UNNAMED",
        ]

        modules = [
            java.desktop,
            java.logging,
            java.prefs,
            java.sql,
            jdk.unsupported
        ]
    }

    mac {
        info-plist {
            "com.apple.developer.associated-domains" = [
                "applinks:hq.com"
            ]
        }
    }

    windows.manifest.application.extensions = [
            {
                category = "windows.appUriHandler",
                host = "hq.com"
            }
        ]
}

windows {
    installer-type = "msix"

    start-menu = true
    desktop = true

    console = false

    certificate = "self-signed"
}

linux {
    installer-type = "deb"
    applications-menu = true

    desktop-file {
        Name = "Help Quest"
        Type = "Application"
        Exec = "helpquest %u"
        categories = ["Network", "Chat"]
        keywords = ["chat", "messaging", "helpquest", "quest"]
        mime-types = ["x-scheme-handler/helpquest"]
    }
}

conveyor {
    compatibility-level = 19
    billing-email = "ferrarini.and@gmail.com"
}